### ISSUE TITLE
Replace sources with https://github.com/cquiroz/scala-java-time and release new version

### ISSUE THREAD

**Issue by domdorn** [scala-js/scala-js-java-time#62]
I just spent many hours trying to figure out why an application I'm trying to build is behaving differently between sbt 1.28 and sbt 1.3.13 and figured out that in sbt 1.3.13 this library was placed before `scala-java-time` in the compile classpath and then throwing errors during compile. 

As this project is hosted under the `scala-js` namespace, developers expect the library to be more complete than the one linked at https://github.com/cquiroz/scala-java-time . They would not expect that the "official" library is making problems. 

To follow the principle of least surprise, I suggest the following: 

Please coordinate with @cquiroz and replace the code in this library with his, 
then release a new version 1.0.1 to maven central. 

For reference, this is the problem I've stumbled upon: 
https://stackoverflow.com/questions/65063755/scalajs-zio-program-works-with-sbt-1-2-8-but-not-1-3/65275462#65275462

**Comment by sjrd** [comment]
Have you read the README of this project?

**Comment by domdorn** [comment]
Yes, and by the status of this project (and its prominent `org.scalajs` organization name), 
in its current state, its making more trouble than helping. 
People expect projects under the `org.scalajs` organization to be somekind stable
and complete, especially if they have a 1.0 version.

**Comment by sjrd** [comment]
I understand what you're saying. However, I still disagree with the solution you're proposing.

We marked this project as deprecated and clearly pointed to its replacement. If the "official" project points to another one, that makes that project official. We are not maintaining this project. We haven't been for a while. The other project is maintained, by maintainers who actually use it. We don't use any of this stuff. We don't have the capacity or the knowledge to maintain it. So we won't.

**Comment by gzm0** [comment]
Reading trough this conversation, it is not 100% clear to me what @domdorn is asking. @domdorn, are you asking for:

1. Ongoing development* in this repository supervised by the Scala.js core maintainers.
2. An even clearer way for users to see that this repository should not be used.
3. Something else?

I'm afraid (as @sjrd pointed out), we cannot offer (1) due to mere resource/time constraints.

As far as (2) goes, I think we are all on the same page that we should make it as clear as possible that this project should not be used.

However, I'm not sure what you are proposing (forward merging sources) is the most effective solution: This is quite the overhead for the Scala.js core maintainers and likely to be forgotten, basically putting us in the same spot we are now 6 months down the line (two libraries are published, one of them is out of date).

Options I can see to redirect devs to the right artifact:
- GitHub: Archive this repository. This should make it very clear for folks arriving from GitHub that this is not to be used (GitHub seems to display a [message bar](https://github.blog/2017-11-08-archiving-repositories/)).
- Maven: We could set the [`relocation`](http://maven.apache.org/ref/3.2.1/maven-model/maven.html#class_relocation) field in a last version to publish (also see [MNG-3952](https://issues.apache.org/jira/browse/MNG-3952), [MNG-5604](https://issues.apache.org/jira/browse/MNG-5604)). I do not know to what extent package managers actually warn if this is present, but at least the metadata would be correct.


*by that I mean actually development, not just procedural merging of code that lives somewhere else.

**Comment by domdorn** [comment]
The problem is not people finding this library through github / google, cause they will already see the deprecation warning and can already chose to go down a different path.

The problem comes 
1.) from people that are using their IDE or 
2.) from people that use websites like  https://mvnrepository.com/artifact/org.scala-js/scalajs-java-time to look for dependencies with a reasonable name to solve their problem. 
3.) from people using software like scala-steward to keep their dependencies up2date
4.) from people using existing projects, upgrading versions of other tools (e.g. sbt 1.2 -> 1.3) and suddently run into problems.


I propose the following steps:

1. offer @cquiroz to move his project under the official scalajs umbrella with the organizationId and artifactId of this repo, so that one working library under the org.scalajs namespace exists, then release a new version so that people will upgrade to it. 
2. if @cquiroz does not want to move his project, then 
2.1a mark all code as deprecated - or something similar which will print out a compiler warning, stating to read the readme of this project and migrate away 
2.1b alternatively remove all code, so that users will download a empty jar and because of the resulting compile errors "fail fast" and will look for a solution 
2.2 release a new version with the deprecated methods/removed methods
2.3 and the maven relocation field turned on to point to @cquiroz repository. 

@gzm0: So what I'm asking for is a mixture of 1, 2, and 3.
Imho the perfect solution would be 1, where @cquiroz would develop here and gets as much help as possible from scalajs maintainers. 
or
2: an even clearer way that this code should not be used, as outlined above (2.1 - 2.3)

3: if we can't bring @cquirez to move his code here (1) AND we are not able to somehow make it foolproof to not use this library anymore (2) (through compiler warnings and/or maven things), then a solution would be to simply (3)
 - regularly pull changes from @cquirez repo to this one 
 - change the organizationId and artifactId
 - release new versions whenever he releases

**Comment by sjrd** [comment]
1. is not an option. We (I at least) *want* this code to be maintained outside of the scala-js organization, under a different organization, because we want to make it clear that it's OK for third-party maintainers to develop quality JDK extensions (and other kinds of libraries). Bringing one under org.scala-js would make the case even *stronger* that what's not in org.scala-js is not to be trusted. We don't want that to happen.
2. ..
  2.1 Unfortunately, that is technically not possible, because calls to JDK APIs compile against the original JDK .class files, which don't have the deprecations.
    2.1.b How is that better than [what you ran into](https://stackoverflow.com/questions/65063755/scalajs-zio-program-works-with-sbt-1-2-8-but-not-1-3/65275462#65275462)?
3. "would be to simply [pull changes and do work]". That's just busywork. No thank you.

The only possibility I see here would be:
* Someone make sure that scala-java-time contains *everything* that this library contains (so that "upgrading" does not break anything)
* Publish a version 2.0.0 with no sources and a dependency on scala-java-time (and a `relocation` field), which would act as a meta-package.

**Comment by gzm0** [comment]
Just to provide my POV on this:

@domdorn In the list of problems you describe, 1 - 3 are essentially a missing deprecation "flag" from the maven side (assuming IDEs pull in stuff via maven). I agree that we should fix this. @sjrd's meta-package proposal seems to address this (as good as we can).

Problem 4 is simply an instance of cargo-culting. I do not see how we can fix this.

As far as the proposed steps are concerned:

1. I second @sjrd's opinion. Maven organizations should reflect actual organizations. Further, this would set a precedent that it is not OK to discontinue/fork a project. IMHO this is not a message we'd like to send.

2. IMO this is what we should do on a higher level, unfortunately only 2.3 (IMO) actually addresses the problem (primarily due to technical constraints).

3. This is merely a poor mans way of implementing (1) *and* causes an untenable amount of busywork. I really do not think this is a good idea.

**Comment by domdorn** [comment]
As to "2.1.b How is that better than what you ran into?" .. it will lead to immediate compile errors, no matter what java.time code is used instead of delayed compile errors, when sometimes later a currently not implemented part is called. This will result into looking at the library instead of the developer thinking "did I do something wrong in the code I just added?". 

In the end, any of the solutions is good as long as people will be lead directly to a solution or at least a solution finding path without spending hours figuring out why their code is suddenly not working anymore. And here I prefer a solution which brakes delibaretely when using the 1.0.1 version of `scalajs-java-time` rather later on when using a feature not yet supported. 

As the scalajs compiler is created by developers of this organization, it maybe would even be possible to add something like a `META-INF/scalajs-notice.txt` or `META-INF/scalajs-warning.txt` that would be printed by the scalajs compiler when a file like this is found during compilation, allowing library authors to give information to library users.

**Comment by sjrd** [comment]
> As to "2.1.b How is that better than what you ran into?" .. it will lead to immediate compile errors, no matter what java.time code is used instead of delayed compile errors, when sometimes later a currently not implemented part is called.

Unfortunately, for the same reason that deprecation warnings wouldn't show up, compilation errors wouldn't show up either. You'd still have only linking errors.

> As the scalajs compiler is created by developers of this organization, it maybe would even be possible to add something like a `META-INF/scalajs-notice.txt` or `META-INF/scalajs-warning.txt` that would be printed by the scalajs compiler when a file like this is found during compilation, allowing library authors to give information to library users.

There is no reason that this is more necessary for Scala.js libraries than for any other library. So if that is supposed to happen, it should be in generic build tools, like in sbt, rather than in Scala.js-specific stuff.

**Comment by domdorn** [comment]
hmm.. could we hook something into the linker maybe?

**Comment by sjrd** [comment]
No, definitely not. This is not the linker's job.
